apiVersion: updateupdateapps/v1
kind: Deployment
metadata:
  name: updateupdateapp-deployment
  labels:
    updateupdateapp: updateupdateapp
spec:
  replicas: 2
  selector:
    matchLabels:
      updateupdateapp: updateupdateapp
  template:
    metadata:
      labels:
        updateupdateapp: updateupdateapp
    spec:
      containers:
      - name: updateupdateapp
        image: 024942939275.dkr.ecr.us-east-1.amazonaws.com/test123:40 
        ports:
          - containerPort: 80
        resources:
            requests:
              cpu: 500m # 0.5
            limits:
              cpu: 1000m # 1
---
apiVersion: v1
kind: Service
metadata:
  name: updateupdateapp-service
spec:
  selector:
    updateupdateapp: updateupdateapp
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
