apiVersion: updateapps/v1
kind: Deployment
metadata:
  name: updateapp-deployment
  labels:
    updateapp: updateapp
spec:
  replicas: 2
  selector:
    matchLabels:
      updateapp: updateapp
  template:
    metadata:
      labels:
        updateapp: updateapp
    spec:
      containers:
      - name: updateapp
        image: 024942939275.dkr.ecr.us-east-1.amazonaws.com/test123:40 
        ports:
          - containerPort: 80
        resources:
            requests:
              cpu: 500m # 0.5
            limits:
              cpu: 1000m # 1
---
apiVersion: v1
kind: Service
metadata:
  name: updateapp-service
spec:
  selector:
    updateapp: updateapp
  # type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
